//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrasferimentiVivisol
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GnXcmEntities1 : DbContext
    {
        public GnXcmEntities1()
            : base("name=GnXcmEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uvwWmsDocument> uvwWmsDocument { get; set; }
        public virtual DbSet<uvwWmsDocumentRows_XCM> uvwWmsDocumentRows_XCM { get; set; }
    }
}
