//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public string User_ID { get; set; }
        public string User_Username { get; set; }
        public string User_Email { get; set; }
        public string User_HashPassword { get; set; }
        public string User_Salt { get; set; }
        public string User_FirstName { get; set; }
        public string User_Surname { get; set; }
        public System.DateTime User_CreationDate { get; set; }
        public System.DateTime User_LastModifiedDate { get; set; }
        public Nullable<bool> User_Active { get; set; }
        public bool User_PasswordRecovered { get; set; }
        public string User_CustomerId { get; set; }
        public Nullable<long> FK_User_Role_ID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
