//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.UNITEX
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        public long ID { get; set; }
        public string EMAIL { get; set; }
        public string PASSWORD { get; set; }
    }
}
