//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lotti
    {
        public string Materiale { get; set; }
        public string Lotto { get; set; }
        public string LottoEsterno { get; set; }
        public string Descrizione { get; set; }
        public string DescrizioneInglese { get; set; }
        public string StatoAnalitico { get; set; }
        public System.DateTime DataGiudizio { get; set; }
        public System.DateTime DataUltimoAggiornamento { get; set; }
    }
}
