//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPassValidator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessi
    {
        public long ID_ACCESSO { get; set; }
        public System.DateTime DATA_VERIFICA { get; set; }
        public long FK_UTENTE { get; set; }
        public System.DateTime ORA_INGRESSO { get; set; }
        public Nullable<System.DateTime> ORA_USCITA { get; set; }
        public string NOTE { get; set; }
        public bool IS_OSPITE { get; set; }
        public string OSPITE_NOME { get; set; }
        public string OSPITE_COGNOME { get; set; }
        public Nullable<System.DateTime> OSPITE_DATA_DI_NASCITA { get; set; }
        public bool IS_FERIE { get; set; }
        public bool IS_MALATTIA { get; set; }
        public bool IS_PERMESSO { get; set; }
        public bool IS_MATERNITA { get; set; }
        public bool IS_CONGEDO_MATRIMONIALE { get; set; }
    
        public virtual Anagrafica Anagrafica { get; set; }
    }
}
