//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenPassValidator
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anagrafica()
        {
            this.Accessi = new HashSet<Accessi>();
        }
    
        public long ID_ANAGRAFICA { get; set; }
        public string NOME { get; set; }
        public string COGNOME { get; set; }
        public System.DateTime DATA_NASCITA { get; set; }
        public string CODICE_FISCALE { get; set; }
        public int LIVELLO { get; set; }
        public string QR_GP_COMUNICATO { get; set; }
        public bool ENABLED { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Accessi> Accessi { get; set; }
    }
}
