//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAGRAFICA_CLIENTI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANAGRAFICA_CLIENTI()
        {
            this.PALLET_IN = new HashSet<PALLET_IN>();
        }
    
        public long ID_ANAGRAFICA_CLIENTE { get; set; }
        public string ID_GESPE { get; set; }
        public string RAGIONE_SOCIALE { get; set; }
        public string EMAIL_COMUNICAZIONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PALLET_IN> PALLET_IN { get; set; }
    }
}
