//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAGRAFICA_CONTENITORI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ANAGRAFICA_CONTENITORI()
        {
            this.REGISTRAZIONE_CONTENITORE = new HashSet<REGISTRAZIONE_CONTENITORE>();
        }
    
        public long ID_ANAGRAFICA_CONTENITORE { get; set; }
        public int TIPO_CONTENITORE { get; set; }
        public string DESCRIZIONE_CONTENITORE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTRAZIONE_CONTENITORE> REGISTRAZIONE_CONTENITORE { get; set; }
    }
}
