//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTRAZIONE_CONTENITORE
    {
        public long ID_REGISTRAZIONE_CONTENITORE { get; set; }
        public long ID_DOCUMENTO { get; set; }
        public long ANAGRAFICA_CONTENITORE { get; set; }
        public int QUANTITA_CONTENITORE { get; set; }
    
        public virtual ANAGRAFICA_CONTENITORI ANAGRAFICA_CONTENITORI { get; set; }
    }
}
