//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSC_LISTINI
    {
        public long ID_LISTINO_TMS { get; set; }
        public string ID_GESPE { get; set; }
        public string REGIONE { get; set; }
        public decimal FASCIA_PESO_DA { get; set; }
        public decimal FASCIA_PESO_A { get; set; }
        public decimal PREZZO { get; set; }
    }
}
