//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSC_SCAGLIONI
    {
        public long ID_SCAGLIONE { get; set; }
        public string ID_GESPE { get; set; }
        public decimal SCAGLIONE_PESO { get; set; }
        public decimal SCAGLIONE_PREZZO { get; set; }
        public string REGIONE { get; set; }
    }
}
