//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSF_G_LISTINI
    {
        public long ID_G_TMSF_LISTINO { get; set; }
        public long FK_TMSF_FORNITORE { get; set; }
        public long FK_TMSF_ACCESSORIO_LISTINO { get; set; }
        public long FK_GEOC { get; set; }
        public decimal PREZZO { get; set; }
        public Nullable<decimal> PERCENTUALE_MAGGIORAZIONE { get; set; }
    
        public virtual GEO_IT_CAPOLUOGO GEO_IT_CAPOLUOGO { get; set; }
        public virtual TMSF_ANAGRAFICA_ACCESSORI_LISTINI TMSF_ANAGRAFICA_ACCESSORI_LISTINI { get; set; }
        public virtual TMSF_FORNITORI TMSF_FORNITORI { get; set; }
    }
}
