//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSF_LISTINI
    {
        public long ID_LISTINO_FORNITORE_TMS { get; set; }
        public long FK_FORNITORE { get; set; }
        public string REGIONE { get; set; }
        public decimal FASCIA_DI_PESO_DA { get; set; }
        public decimal FASCIA_DI_PESO_A { get; set; }
        public decimal COSTO { get; set; }
    
        public virtual TMSF_FORNITORI TMSF_FORNITORI { get; set; }
    }
}
