//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMSF_ANAGRAFICA_ACCESSORI_LISTINI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TMSF_ANAGRAFICA_ACCESSORI_LISTINI()
        {
            this.TMSF_G_LISTINI = new HashSet<TMSF_G_LISTINI>();
        }
    
        public long ID_ANAGRAFICA_ACCESSORIO { get; set; }
        public string DESCRIZIONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TMSF_G_LISTINI> TMSF_G_LISTINI { get; set; }
    }
}
