//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmsShipmentMovGoods
    {
        public Nullable<short> RowNumber { get; set; }
        public string HolderID { get; set; }
        public string GoodsCode { get; set; }
        public string GoodsType { get; set; }
        public string GoodsPackaging { get; set; }
        public Nullable<decimal> GoodsValue { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Packs { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Deep { get; set; }
        public Nullable<decimal> Cube { get; set; }
        public Nullable<decimal> Meters { get; set; }
        public Nullable<int> Pallets { get; set; }
        public string Documents { get; set; }
        public string ContainerType { get; set; }
        public string PacksType { get; set; }
        public string Seal { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string RefusedCode { get; set; }
        public Nullable<int> AdrID { get; set; }
        public string ItemInfo { get; set; }
        public int Uniq { get; set; }
        public Nullable<int> UniqMov { get; set; }
        public Nullable<int> UniqDoc { get; set; }
        public Nullable<int> UniqLeg { get; set; }
        public Nullable<System.DateTime> RowCreate { get; set; }
        public Nullable<short> RowUserID { get; set; }
        public Nullable<System.DateTime> RowChange { get; set; }
        public Nullable<short> RowChangeUserID { get; set; }
        public Nullable<bool> RowLocked { get; set; }
        public Nullable<byte> RowType { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Seat { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string CustomsID { get; set; }
        public string PacksTypeID { get; set; }
        public Nullable<int> LegLoadID { get; set; }
        public Nullable<int> LegUnloadID { get; set; }
        public string UnitsDimension { get; set; }
        public Nullable<int> PalletsTotal { get; set; }
        public string PalletsID { get; set; }
        public string CER { get; set; }
        public string NasID { get; set; }
        public string NasDes { get; set; }
        public string WagonID { get; set; }
        public Nullable<int> NumStackable { get; set; }
        public Nullable<bool> IsStackable { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string MarksNumbers { get; set; }
        public Nullable<int> IdCompany { get; set; }
        public string ItemBooking { get; set; }
        public string CustomsVoiceDes { get; set; }
    }
}
