//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvwGrdTmsShipmentMovGoods_Detail
    {
        public int Rows { get; set; }
        public int Row { get; set; }
        public Nullable<byte> DocTip { get; set; }
        public string DocNum { get; set; }
        public Nullable<System.DateTime> DocDta { get; set; }
        public string buttonPlus { get; set; }
        public string buttonOpen { get; set; }
        public Nullable<short> RowNumber { get; set; }
        public string HolderID { get; set; }
        public string GoodsCode { get; set; }
        public string GoodsType { get; set; }
        public string GoodsPackaging { get; set; }
        public Nullable<decimal> GoodsValue { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Packs { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Deep { get; set; }
        public Nullable<decimal> Cube { get; set; }
        public Nullable<decimal> Meters { get; set; }
        public Nullable<int> Pallets { get; set; }
        public string Documents { get; set; }
        public string ContainerType { get; set; }
        public string PacksType { get; set; }
        public string Seal { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string RefusedCode { get; set; }
        public string ItemInfo { get; set; }
        public int Uniq { get; set; }
        public Nullable<int> UniqMov { get; set; }
        public Nullable<int> UniqDoc { get; set; }
        public Nullable<int> UniqLeg { get; set; }
        public Nullable<System.DateTime> RowCreate { get; set; }
        public Nullable<short> RowUserID { get; set; }
        public Nullable<System.DateTime> RowChange { get; set; }
        public Nullable<short> RowChangeUserID { get; set; }
        public Nullable<bool> RowLocked { get; set; }
        public Nullable<byte> RowType { get; set; }
        public string ReferenceType { get; set; }
        public Nullable<System.DateTime> ReferenceDate { get; set; }
        public string Reference { get; set; }
        public Nullable<decimal> Seat { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string CustomsID { get; set; }
        public string CustomsVoice_ItemDesShort { get; set; }
        public Nullable<int> AdrID { get; set; }
        public string C_1_un { get; set; }
        public string C_2a_name_it { get; set; }
        public string C_3b_code { get; set; }
        public string C_5_label { get; set; }
        public Nullable<int> UniqShipment { get; set; }
        public string Filler { get; set; }
    }
}
