//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvwTmsShipment
    {
        public string ServiceType { get; set; }
        public string TransportType { get; set; }
        public string CarrierType { get; set; }
        public int Corrected { get; set; }
        public bool CreditInvoiceOk { get; set; }
        public Nullable<bool> Invoiced { get; set; }
        public Nullable<bool> InvoicedNotTotal { get; set; }
        public Nullable<short> PriorityCode { get; set; }
        public byte DocTip { get; set; }
        public string DocNum { get; set; }
        public Nullable<System.DateTime> DocDta { get; set; }
        public string InvoiceReason { get; set; }
        public string AnaDes1 { get; set; }
        public string Senders { get; set; }
        public string Loads { get; set; }
        public string Consignee { get; set; }
        public string Unloads { get; set; }
        public Nullable<System.DateTime> UnloadsDate { get; set; }
        public Nullable<int> Packs { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Cube { get; set; }
        public string VehiclePlate { get; set; }
        public string TowPlate { get; set; }
        public string DriverDes1 { get; set; }
        public Nullable<decimal> DocCredit { get; set; }
        public string AnaDes2 { get; set; }
        public Nullable<decimal> DocDebit { get; set; }
        public string ExternRef { get; set; }
        public string Documents { get; set; }
        public int Uniq { get; set; }
        public int Adr { get; set; }
        public Nullable<System.DateTime> RecCreate { get; set; }
        public Nullable<short> RecUserID { get; set; }
        public Nullable<System.DateTime> RecChange { get; set; }
        public Nullable<short> RecChangeUserID { get; set; }
        public Nullable<byte> RecCompany { get; set; }
        public Nullable<byte> RecAgency { get; set; }
        public string ItemColor { get; set; }
        public Nullable<byte> DocStatus { get; set; }
    }
}
