//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvwWmsDocumentRows_XCM
    {
        public int uniq { get; set; }
        public Nullable<byte> DocTip { get; set; }
        public int RowID { get; set; }
        public Nullable<int> RowIdLink { get; set; }
        public string DocNum { get; set; }
        public string DocNum2 { get; set; }
        public Nullable<System.DateTime> DocDta { get; set; }
        public string DocDes { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> RefDta { get; set; }
        public string Reference2 { get; set; }
        public Nullable<System.DateTime> RefDta2 { get; set; }
        public Nullable<int> AnaType { get; set; }
        public string AnaId { get; set; }
        public string Anades { get; set; }
        public string AnaVatCode { get; set; }
        public Nullable<System.DateTime> RecCreate { get; set; }
        public Nullable<int> RecUserID { get; set; }
        public Nullable<System.DateTime> RecChange { get; set; }
        public Nullable<int> RecChangeUserID { get; set; }
        public string NumCod { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Priority { get; set; }
        public string CustomerID { get; set; }
        public string CustomerDes { get; set; }
        public string CustomerAdress { get; set; }
        public string CustomerLoc { get; set; }
        public string CustomerProv { get; set; }
        public string CustomerCAP { get; set; }
        public string CustomerReg { get; set; }
        public string CustomerNaz { get; set; }
        public string CustomerPIva { get; set; }
        public string PagCod { get; set; }
        public Nullable<int> OwnerType { get; set; }
        public string OwnerID { get; set; }
        public string OwnerDes { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string SenderZipCode { get; set; }
        public string SenderLocation { get; set; }
        public string SenderDistrict { get; set; }
        public string SenderRegion { get; set; }
        public string SenderCountry { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ConsigneeZipCode { get; set; }
        public string ConsigneeLocation { get; set; }
        public string ConsigneeDistrict { get; set; }
        public string ConsigneeRegion { get; set; }
        public string ConsigneeCountry { get; set; }
        public Nullable<int> UnloadID { get; set; }
        public string UnloadName { get; set; }
        public string UnloadAddress { get; set; }
        public string UnloadZipCode { get; set; }
        public string UnloadLocation { get; set; }
        public string UnloadDistrict { get; set; }
        public string UnloadRegion { get; set; }
        public string UnloadCountry { get; set; }
        public string UnloadPhoneNumber { get; set; }
        public string LogWareID { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public string StatusTypeFrom { get; set; }
        public string SiteID { get; set; }
        public string TxToSiteId { get; set; }
        public Nullable<System.DateTime> ShipDta { get; set; }
        public Nullable<int> PltFloor { get; set; }
        public string ShipBy { get; set; }
        public Nullable<int> DocProcId { get; set; }
        public string StatusDes { get; set; }
        public string ItemColor { get; set; }
        public string StatusType { get; set; }
        public string PrdCod { get; set; }
        public string PrdDes { get; set; }
        public string Batchno { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public Nullable<System.DateTime> DateProd { get; set; }
        public string Prdum { get; set; }
        public string PrdUm2 { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> QtyUm2 { get; set; }
        public Nullable<decimal> PrdUm2Rap { get; set; }
        public Nullable<decimal> Packs { get; set; }
        public Nullable<decimal> Boxes { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> Cube { get; set; }
        public string PackageID { get; set; }
        public Nullable<decimal> Pallets { get; set; }
        public string Project { get; set; }
        public string SubProject { get; set; }
        public string BarcodeExt { get; set; }
        public string ItemNote { get; set; }
        public string RegTypeID { get; set; }
        public string RegTypeDes { get; set; }
        public string RegTypeDocDes { get; set; }
        public Nullable<decimal> QtyUsed { get; set; }
        public string IncotermID { get; set; }
        public string IncotermType { get; set; }
        public string IncotermDes { get; set; }
        public string ShipDocNum { get; set; }
        public decimal QtyCovered { get; set; }
        public decimal QtyPlanned { get; set; }
        public decimal QtyExecuted { get; set; }
        public int GrdPltOut { get; set; }
        public string SiteSupplierDes { get; set; }
        public string SiteSupplierAddress { get; set; }
        public string SiteSupplierZipCode { get; set; }
        public string SiteSUpplierLocation { get; set; }
        public string SiteSupplierDistrict { get; set; }
        public string CarrierDes { get; set; }
        public string CarrierAddress { get; set; }
        public string CarrierZipCode { get; set; }
        public string CarrierLocation { get; set; }
        public string CarrierDistrict { get; set; }
        public Nullable<System.DateTime> ShelfLifeDta { get; set; }
        public Nullable<System.DateTime> TripStartDta { get; set; }
        public string TripDocNum { get; set; }
        public string TripHolderID { get; set; }
        public string TripServiceType { get; set; }
        public string TripTransportType { get; set; }
        public string PrdCat { get; set; }
        public string PrdGrp { get; set; }
        public string PrdTree { get; set; }
        public string HeaderInfo1 { get; set; }
        public string HeaderInfo2 { get; set; }
        public string HeaderInfo3 { get; set; }
        public string HeaderInfo4 { get; set; }
        public string HeaderInfo5 { get; set; }
        public string HeaderInfo6 { get; set; }
        public string HeaderInfo7 { get; set; }
        public string HeaderInfo8 { get; set; }
        public string HeaderInfo9 { get; set; }
        public string HeaderDeliveryDock { get; set; }
        public string Info { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> NetSellPrice { get; set; }
        public string RowInfo1 { get; set; }
        public string RowInfo2 { get; set; }
        public string RowInfo3 { get; set; }
        public string RowInfo4 { get; set; }
        public string RowInfo5 { get; set; }
        public string RowInfo6 { get; set; }
        public string RowInfo7 { get; set; }
        public string RowInfo8 { get; set; }
        public string RowInfo9 { get; set; }
        public string DeliveryDock { get; set; }
        public Nullable<decimal> QtyOriginal { get; set; }
        public Nullable<decimal> GrdPackQty { get; set; }
        public Nullable<int> GrdPacksNo { get; set; }
        public string Producer { get; set; }
        public decimal QtyChecked { get; set; }
        public Nullable<decimal> GrdCostPrice { get; set; }
        public Nullable<decimal> GrdSellPrice { get; set; }
        public Nullable<decimal> CostPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public string CostTypeID { get; set; }
        public string SellTypeID { get; set; }
        public string Variant1 { get; set; }
        public string Variant2 { get; set; }
        public string Variant3 { get; set; }
        public string Variant4 { get; set; }
        public string Variant5 { get; set; }
        public Nullable<decimal> CashValue { get; set; }
        public Nullable<int> LblOut { get; set; }
        public string AliasID { get; set; }
        public string MemoMessage { get; set; }
        public string VatID { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public string ORderDocNum { get; set; }
    }
}
