//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovimentiMagazzinoFromGespe
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XCM_WMSEntities : DbContext
    {
        public XCM_WMSEntities()
            : base("name=XCM_WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ANAGRAFICA_CLIENTI> ANAGRAFICA_CLIENTI { get; set; }
        public virtual DbSet<ANAGRAFICA_OPERATORI> ANAGRAFICA_OPERATORI { get; set; }
        public virtual DbSet<GEO_IT> GEO_IT { get; set; }
        public virtual DbSet<GEO_IT_CAPOLUOGO> GEO_IT_CAPOLUOGO { get; set; }
        public virtual DbSet<PALLET_IN> PALLET_IN { get; set; }
        public virtual DbSet<PALLET_MAX> PALLET_MAX { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TMSC_LISTINI> TMSC_LISTINI { get; set; }
        public virtual DbSet<TMSC_SCAGLIONI> TMSC_SCAGLIONI { get; set; }
        public virtual DbSet<TMSF_ANAGRAFICA_ACCESSORI_LISTINI> TMSF_ANAGRAFICA_ACCESSORI_LISTINI { get; set; }
        public virtual DbSet<TMSF_FORNITORI> TMSF_FORNITORI { get; set; }
        public virtual DbSet<TMSF_G_LISTINI> TMSF_G_LISTINI { get; set; }
        public virtual DbSet<TMSF_LISTINI> TMSF_LISTINI { get; set; }
    }
}
