//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAGRAFICA_CLIENTI
    {
        public long ID_ANAGRAFICA_CLIENTE { get; set; }
        public string ID_GESPE { get; set; }
        public string RAGIONE_SOCIALE { get; set; }
        public string EMAIL_COMUNICAZIONE { get; set; }
    }
}
