//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEO_IT
    {
        public long ID_GEOGRAFICO { get; set; }
        public string CAP { get; set; }
        public string CITTA { get; set; }
        public string REGIONE { get; set; }
        public string PROVINCIA { get; set; }
        public Nullable<int> ABITANTI { get; set; }
        public string CODICE_ISTAT { get; set; }
    }
}
