//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeoZipCode
    {
        public string ItemCode { get; set; }
        public string ItemName { get; set; }
        public string CountryName { get; set; }
        public string RegionName { get; set; }
        public string DistrictCode { get; set; }
        public string TransitID { get; set; }
        public string TourID { get; set; }
        public Nullable<bool> ItemDown { get; set; }
        public Nullable<bool> ItemChief { get; set; }
        public string Area { get; set; }
        public string StatID { get; set; }
        public string StatDes { get; set; }
        public Nullable<int> Population { get; set; }
        public string ItemInfo { get; set; }
        public string IstatCode { get; set; }
        public int ItemID { get; set; }
        public string UNCode { get; set; }
        public Nullable<bool> IsFreeZone { get; set; }
    }
}
