//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GnCommonXcmEntities : DbContext
    {
        public GnCommonXcmEntities()
            : base("name=GnCommonXcmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TmsShipment> TmsShipment { get; set; }
        public virtual DbSet<TmsTrip> TmsTrip { get; set; }
        public virtual DbSet<TmsLeg> TmsLeg { get; set; }
        public virtual DbSet<GeoZipCode> GeoZipCode { get; set; }
    }
}
