//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GnXcmEntities : DbContext
    {
        public GnXcmEntities()
            : base("name=GnXcmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<uvwWmsDocument> uvwWmsDocument { get; set; }
        public virtual DbSet<TmsLocationDetail> TmsLocationDetail { get; set; }
        public virtual DbSet<TmsParcel> TmsParcel { get; set; }
    }
}
