//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmsLocationDetail
    {
        public int UniqRow { get; set; }
        public Nullable<int> LocationID { get; set; }
        public string Name { get; set; }
        public string ZipCode { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string Region { get; set; }
        public string Country { get; set; }
        public Nullable<byte> AnaType { get; set; }
        public string AnaID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<byte> ItemUse { get; set; }
        public string EdiCode { get; set; }
        public string EdiCode2 { get; set; }
        public string EdiCode3 { get; set; }
        public string EmailAddress { get; set; }
    }
}
