//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmsParcel
    {
        public int Uniq { get; set; }
        public string BarCode { get; set; }
        public string BarCodeMaster { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Deep { get; set; }
        public Nullable<decimal> Cube { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public Nullable<decimal> GrossWeight { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public string WmsLocCode { get; set; }
        public string UserCheckIn { get; set; }
        public Nullable<System.DateTime> TsCheckIn { get; set; }
        public string UserCheckOut { get; set; }
        public Nullable<System.DateTime> TsCheckOut { get; set; }
        public string ItemInfo { get; set; }
        public Nullable<System.DateTime> RowCreate { get; set; }
        public Nullable<short> RowUserID { get; set; }
        public Nullable<System.DateTime> RowChange { get; set; }
        public Nullable<short> RowChangeUserID { get; set; }
        public Nullable<int> UniqFrom { get; set; }
        public Nullable<byte> DocTipFrom { get; set; }
        public Nullable<int> UniqLegFrom { get; set; }
        public Nullable<int> UniqWmsFrom { get; set; }
        public Nullable<int> LocID { get; set; }
        public string SiteID { get; set; }
        public string ChkFields { get; set; }
        public string BarCodeExt { get; set; }
        public Nullable<int> Row { get; set; }
        public Nullable<int> UniqMovGoodsFrom { get; set; }
        public string Reference { get; set; }
        public string PrdCod { get; set; }
        public string PdtCod { get; set; }
        public Nullable<int> UniqMovGoodsSupplierFrom { get; set; }
        public Nullable<decimal> Value { get; set; }
        public Nullable<int> IdCompany { get; set; }
        public string LastLog { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public string StatusTypeFrom { get; set; }
        public Nullable<System.DateTime> TrackingDate { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public string LocationInfo { get; set; }
        public Nullable<int> Prg { get; set; }
        public Nullable<int> SortUserID { get; set; }
    }
}
