//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmsShipment
    {
        public byte DocTip { get; set; }
        public string DocNum { get; set; }
        public Nullable<System.DateTime> DocDta { get; set; }
        public string DocTime { get; set; }
        public Nullable<byte> DocUse { get; set; }
        public Nullable<byte> DocStatus { get; set; }
        public string DocDes { get; set; }
        public string DocUnit { get; set; }
        public Nullable<decimal> DocQty { get; set; }
        public string InsideRef { get; set; }
        public string ExternRef { get; set; }
        public string IncotermID { get; set; }
        public string Freight { get; set; }
        public string BusinessUnit { get; set; }
        public string ShipmentType { get; set; }
        public string ServiceType { get; set; }
        public string CarrierType { get; set; }
        public string TransportType { get; set; }
        public string VehicleTypeAsked { get; set; }
        public string VehicleID { get; set; }
        public string VehicleType { get; set; }
        public string TowID { get; set; }
        public string GoodsType { get; set; }
        public Nullable<decimal> GoodsValue { get; set; }
        public Nullable<decimal> DepositValue { get; set; }
        public string Documents { get; set; }
        public Nullable<System.DateTime> DocumentsDate { get; set; }
        public string DriverID1 { get; set; }
        public string DriverID2 { get; set; }
        public string HolderID1 { get; set; }
        public string HolderID2 { get; set; }
        public string TransitID { get; set; }
        public Nullable<int> TripID { get; set; }
        public string TripSheetID { get; set; }
        public string TripList { get; set; }
        public Nullable<bool> TripBack { get; set; }
        public string BackID { get; set; }
        public string CargoTripID { get; set; }
        public Nullable<int> Port { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<decimal> Meters { get; set; }
        public Nullable<decimal> Cube { get; set; }
        public Nullable<decimal> Km { get; set; }
        public Nullable<decimal> KmEmpty { get; set; }
        public Nullable<int> Packs { get; set; }
        public Nullable<int> Pack1 { get; set; }
        public Nullable<int> PackN { get; set; }
        public Nullable<int> PackFree { get; set; }
        public string PalletID { get; set; }
        public Nullable<int> Pallets { get; set; }
        public string Barcodes { get; set; }
        public Nullable<int> TicketNumber { get; set; }
        public Nullable<decimal> TicketValue { get; set; }
        public Nullable<decimal> FuelCost { get; set; }
        public Nullable<decimal> FuelCostPercent { get; set; }
        public Nullable<decimal> FuelFullfillment { get; set; }
        public Nullable<decimal> FuelKm { get; set; }
        public Nullable<byte> CreditSplitType { get; set; }
        public Nullable<byte> DebitSplitType { get; set; }
        public Nullable<bool> CreditInvoiceOk { get; set; }
        public Nullable<bool> DebitInvoiceOk { get; set; }
        public string InvoiceReason { get; set; }
        public Nullable<decimal> FuelCarrierPercent { get; set; }
        public Nullable<decimal> FuelLegKm { get; set; }
        public Nullable<byte> VehicleFuelType { get; set; }
        public Nullable<decimal> CashValue { get; set; }
        public Nullable<bool> IsSenderCash { get; set; }
        public Nullable<bool> IsShippingTaking { get; set; }
        public Nullable<bool> IsDelivered { get; set; }
        public string Info { get; set; }
        public string Info0 { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
        public string Info4 { get; set; }
        public string Info5 { get; set; }
        public string Info6 { get; set; }
        public Nullable<decimal> DocCredit { get; set; }
        public Nullable<decimal> DocDebit { get; set; }
        public Nullable<decimal> DocBalance { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string SenderName { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ConsigneeName { get; set; }
        public string Notify { get; set; }
        public string Notify2 { get; set; }
        public string FinalConsignee { get; set; }
        public string CustomsAgency { get; set; }
        public string NumCod { get; set; }
        public Nullable<int> Numero { get; set; }
        public int Uniq { get; set; }
        public Nullable<System.DateTime> RecCreate { get; set; }
        public Nullable<short> RecUserID { get; set; }
        public Nullable<System.DateTime> RecChange { get; set; }
        public Nullable<short> RecChangeUserID { get; set; }
        public Nullable<byte> RecCompany { get; set; }
        public Nullable<byte> RecAgency { get; set; }
        public Nullable<bool> RecLocked { get; set; }
        public Nullable<byte> RecType { get; set; }
        public Nullable<short> PriorityCode { get; set; }
        public Nullable<decimal> Seat { get; set; }
        public Nullable<decimal> NetWeight { get; set; }
        public string StartAgencyCod { get; set; }
        public string EndAgency { get; set; }
        public string DocumentsGrouped { get; set; }
        public Nullable<int> UniqCustomsExternal { get; set; }
        public string StatusTypeFrom { get; set; }
        public string CashValueCurrency { get; set; }
        public string CashValueType { get; set; }
        public string CashValueNote { get; set; }
        public Nullable<int> StartTransitPointID { get; set; }
        public Nullable<int> EndTransitPointID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string SalesManagerID { get; set; }
        public string ChkFields { get; set; }
        public Nullable<decimal> DocCredit2 { get; set; }
        public string Temperature { get; set; }
        public string StartAgency { get; set; }
        public string TourID_Start { get; set; }
        public string TourID_End { get; set; }
        public Nullable<int> UniqEdiFrom { get; set; }
        public Nullable<System.DateTime> PTVLastUpdate { get; set; }
        public Nullable<short> ManagerID { get; set; }
        public string CodADP { get; set; }
        public string Rubrique { get; set; }
        public string IncotermTypeID { get; set; }
        public Nullable<decimal> KmReal { get; set; }
        public Nullable<decimal> DestPayment { get; set; }
        public Nullable<int> NotifyID { get; set; }
        public string CustomerID { get; set; }
        public string ServiceTypeNetwork { get; set; }
        public string Customer_PriceID { get; set; }
        public string StartZoneID { get; set; }
        public string EndZoneID { get; set; }
        public string StartHubID { get; set; }
        public string DestPaymentType { get; set; }
        public string OwnerAgency { get; set; }
        public Nullable<int> LinkShipStartAgency { get; set; }
        public Nullable<int> LinkShipEndAgency { get; set; }
        public Nullable<int> GroupID_Supplier1 { get; set; }
        public Nullable<int> GroupID_Supplier2 { get; set; }
        public string AirShipmentType { get; set; }
        public string DeliveryAgentName { get; set; }
        public Nullable<int> DeliveryAgentID { get; set; }
        public string SeaShipmentType { get; set; }
        public string CodeRate { get; set; }
        public Nullable<int> IdCompany { get; set; }
        public Nullable<int> IdMasterAnaCustomer { get; set; }
        public string Cig { get; set; }
        public string Cup { get; set; }
        public Nullable<System.DateTime> ShipDateOriStart { get; set; }
        public Nullable<System.DateTime> ShipDateOriEnd { get; set; }
        public string ShipTimeOriStart { get; set; }
        public string ShipTimeOriEnd { get; set; }
        public string ItineraryCod { get; set; }
        public Nullable<System.DateTime> AccrualDate { get; set; }
        public string ExternalId { get; set; }
        public string ExternalId1 { get; set; }
        public string HolderRegTypeID { get; set; }
        public Nullable<int> WebAttachCount { get; set; }
    }
}
