//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XCM_WMSEntities : DbContext
    {
        public XCM_WMSEntities()
            : base("name=XCM_WMSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GEO_IT> GEO_IT { get; set; }
        public virtual DbSet<ANAGRAFICA_CLIENTI> ANAGRAFICA_CLIENTI { get; set; }
    }
}
