//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentAuthorization
    {
        public long AgentAuthorization_ID { get; set; }
        public string FK_AgentAuthorization_User_ID { get; set; }
        public bool AgentAuthorization_OrderConfirmation { get; set; }
        public System.DateTime AgentAuthorization_CreationDate { get; set; }
        public System.DateTime AgentAuthorization_LastModifiedDate { get; set; }
        public string AgentAuthorization_LastModifiedUserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
