//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafica_Prodotti
    {
        public long ID_ANAGRAFICA_PRODOTTO { get; set; }
        public string CODICE_PRODOTTO { get; set; }
        public string DESCRIZIONE_PRODOTTO { get; set; }
        public Nullable<decimal> PREZZO_UNITARIO { get; set; }
        public System.DateTime DATA_CREAZIONE { get; set; }
        public System.DateTime DATA_ULTIMA_MODIFICA { get; set; }
        public string GESPE_CUSTOMERID { get; set; }
    }
}
