//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie_Prodotti
    {
        public long ID_CATEGORIA { get; set; }
        public string DESCRIZIONE { get; set; }
        public decimal PERCENTUALE_COMMISSIONE { get; set; }
    }
}
