//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cd_PG
    {
        public long Cd_PG_ID { get; set; }
        public string Codice_PG { get; set; }
        public string Cd_PG_Description { get; set; }
        public int Cd_PG_NumeroRate { get; set; }
        public int Cd_PG_AccontoPercentuale { get; set; }
        public string Cd_PG_PartenzaScadenze { get; set; }
        public int Cd_PG_NumeroGiorni { get; set; }
    }
}
