//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client_User
    {
        public string UserClient_UserID { get; set; }
        public string UserClient_Name { get; set; }
        public string FK_UserClient_Customer_ID { get; set; }
        public System.DateTime UserClient_CreationDate { get; set; }
        public System.DateTime UserClient_LastModifiedDate { get; set; }
        public string UserClient_LastModifiedUserID { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
