//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Client
    {
        public string Client_Id { get; set; }
        public long Client_ProgressiveId { get; set; }
        public string Client_ExtId { get; set; }
        public string Client_Description { get; set; }
        public string Client_PartitaIVA { get; set; }
        public string Client_CodiceFiscale { get; set; }
        public string Client_IBAN { get; set; }
        public string Client_Phone { get; set; }
        public string Client_Email { get; set; }
        public bool Client_IsActive { get; set; }
        public string Client_CodicePagamento { get; set; }
        public string Client_CodiceFPR { get; set; }
        public string Client_CodiceIPA { get; set; }
        public Nullable<bool> Client_EntePubblico { get; set; }
        public string Client_TipoDitta { get; set; }
        public System.DateTime Client_CreationDate { get; set; }
        public System.DateTime Client_LastModifiedDate { get; set; }
        public string Client_LastModifiedUserID { get; set; }
        public string FK_Client_Customer_Id { get; set; }
    }
}
