//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Podotto_Categoria
    {
        public long ID_Prodotto_Categoria { get; set; }
        public long FK_ANAGRAFICA_ARTICOLO { get; set; }
        public long FK_CATEGORIA { get; set; }
    }
}
