//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEO
    {
        public long LOCATION_ID { get; set; }
        public string LOCATION_VIA { get; set; }
        public string LOCATION_STRADA { get; set; }
        public int LOCATION_NCIVICO { get; set; }
        public string LOCATION_CAP { get; set; }
        public string LOCATION_LOCATION { get; set; }
        public string LOCATION_PROVINCIA { get; set; }
        public string LOCATION_NAZIONE { get; set; }
    }
}
