//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Order_Agent = new HashSet<Order_Agent>();
        }
    
        public long Orders_XcmID { get; set; }
        public string Orders_docNumber { get; set; }
        public System.DateTime Orders_docDate { get; set; }
        public string Orders_statusDes { get; set; }
        public string Orders_reference { get; set; }
        public System.DateTime Orders_referenceDate { get; set; }
        public string Orders_reTypeID { get; set; }
        public string Orders_senderDes { get; set; }
        public string Orders_consigneeDes { get; set; }
        public string Orders_unloadDes { get; set; }
        public string Orders_customerDes { get; set; }
        public string Orders_customerID { get; set; }
        public string Orders_siteID { get; set; }
        public Nullable<long> Orders_shipID { get; set; }
        public string Orders_shipDocNumber { get; set; }
        public Nullable<long> Orders_tripID { get; set; }
        public string Orders_tripDocNumber { get; set; }
        public int Orders_statusId { get; set; }
        public string Orders_reference2 { get; set; }
        public Nullable<System.DateTime> Orders_reference2Date { get; set; }
        public string Orders_externalID { get; set; }
        public string Orders_ownerID { get; set; }
        public string Orders_ownerDes { get; set; }
        public Nullable<int> Orders_senderID { get; set; }
        public string Orders_senderAddress { get; set; }
        public string Orders_senderZipCode { get; set; }
        public string Orders_senderLocation { get; set; }
        public string Orders_senderDistrict { get; set; }
        public string Orders_senderRegion { get; set; }
        public string Orders_senderCountry { get; set; }
        public Nullable<long> Orders_consigneeID { get; set; }
        public string Orders_consigneeAddress { get; set; }
        public string Orders_consigneeZipCode { get; set; }
        public string Orders_consigneeLocation { get; set; }
        public string Orders_consigneeDistrict { get; set; }
        public string Orders_consigneeRegion { get; set; }
        public string Orders_consigneeCountry { get; set; }
        public Nullable<long> Orders_unloadID { get; set; }
        public string Orders_unloadAddress { get; set; }
        public string Orders_unloadZipCode { get; set; }
        public string Orders_unloadLocation { get; set; }
        public string Orders_unloadDistrict { get; set; }
        public string Orders_unloadRegion { get; set; }
        public string Orders_unloadCountry { get; set; }
        public Nullable<int> Orders_rowsNo { get; set; }
        public Nullable<decimal> Orders_totalQty { get; set; }
        public Nullable<decimal> Orders_totalPacks { get; set; }
        public Nullable<decimal> Orders_totalBoxes { get; set; }
        public Nullable<decimal> Orders_totalNetWeight { get; set; }
        public Nullable<decimal> Orders_totalGrossWeight { get; set; }
        public Nullable<decimal> Orders_totalCube { get; set; }
        public Nullable<decimal> Orders_coverage { get; set; }
        public Nullable<decimal> Orders_planned { get; set; }
        public Nullable<decimal> Orders_executed { get; set; }
        public string Orders_internalNote { get; set; }
        public string Orders_publicNote { get; set; }
        public string Orders_deliveryNote { get; set; }
        public string Orders_info1 { get; set; }
        public string Orders_info2 { get; set; }
        public string Orders_info3 { get; set; }
        public string Orders_info4 { get; set; }
        public string Orders_info5 { get; set; }
        public string Orders_info6 { get; set; }
        public string Orders_info7 { get; set; }
        public string Orders_info8 { get; set; }
        public string Orders_info9 { get; set; }
        public long Orders_GespeUniq { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Agent> Order_Agent { get; set; }
    }
}
