//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Temp_Orders()
        {
            this.Temp_Order_Products = new HashSet<Temp_Order_Products>();
        }
    
        public long OrderID { get; set; }
        public string CustomerID { get; set; }
        public string AgentID { get; set; }
        public long UnloadLocationID { get; set; }
        public Nullable<long> ConsigneeLocationID { get; set; }
        public string OrderType { get; set; }
        public string OrderReference { get; set; }
        public System.DateTime OrderReferenceDate { get; set; }
        public string XCMNote { get; set; }
        public string DeliveryNote { get; set; }
        public bool OrderConfirmed { get; set; }
        public bool OrderSended { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Temp_Order_Products> Temp_Order_Products { get; set; }
    }
}
