//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temp_Order_Products
    {
        public long ID { get; set; }
        public long Order_ID { get; set; }
        public string Product_PartNumber { get; set; }
        public string Product_Des { get; set; }
        public int Product_Quantity { get; set; }
        public decimal Product_Price { get; set; }
        public decimal Product_Discount { get; set; }
        public decimal Product_Iva { get; set; }
    
        public virtual Temp_Orders Temp_Orders { get; set; }
    }
}
