//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public long ID_TRACKING { get; set; }
        public long Tracking_ShipmentID { get; set; }
        public System.DateTime Tracking_Data { get; set; }
        public int Tracking_StatusID { get; set; }
        public string Tracking_StatusDes { get; set; }
    
        public virtual ShipmentList ShipmentList { get; set; }
    }
}
