//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_XCM.Models.XCM.CRM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XCM_CRMEntities : DbContext
    {
        public XCM_CRMEntities()
            : base("name=XCM_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Client_User> Client_User { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Customer_Authorization> Customer_Authorization { get; set; }
        public virtual DbSet<Customer_Location> Customer_Location { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<ShipmentList> ShipmentList { get; set; }
        public virtual DbSet<Tracking> Tracking { get; set; }
        public virtual DbSet<AgentAuthorization> AgentAuthorization { get; set; }
        public virtual DbSet<Temp_Orders> Temp_Orders { get; set; }
        public virtual DbSet<Anagrafica_Prodotti> Anagrafica_Prodotti { get; set; }
        public virtual DbSet<Order_Agent> Order_Agent { get; set; }
        public virtual DbSet<Temp_Order_Products> Temp_Order_Products { get; set; }
    }
}
