//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VivisolPalletXCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvwWmsDocument
    {
        public int uniq { get; set; }
        public Nullable<byte> DocTip { get; set; }
        public string DocType { get; set; }
        public string DocNum { get; set; }
        public string DocNum2 { get; set; }
        public Nullable<System.DateTime> DocDta { get; set; }
        public string DocDes { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> RefDta { get; set; }
        public string Reference2 { get; set; }
        public Nullable<System.DateTime> RefDta2 { get; set; }
        public Nullable<int> AnaType { get; set; }
        public string AnaId { get; set; }
        public string Priority { get; set; }
        public string RegTypeID { get; set; }
        public byte Coverage { get; set; }
        public byte Planned { get; set; }
        public byte Executed { get; set; }
        public string Anades { get; set; }
        public Nullable<System.DateTime> RecCreate { get; set; }
        public Nullable<int> RecUserID { get; set; }
        public Nullable<System.DateTime> RecChange { get; set; }
        public Nullable<int> RecChangeUserID { get; set; }
        public string NumCod { get; set; }
        public Nullable<int> Numero { get; set; }
        public string CustomerID { get; set; }
        public string CustomerDes { get; set; }
        public Nullable<int> OwnerType { get; set; }
        public string OwnerID { get; set; }
        public string OwnerDes { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string SenderZipCode { get; set; }
        public string SenderLocation { get; set; }
        public string SenderDistrict { get; set; }
        public string SenderRegion { get; set; }
        public string SenderCountry { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ConsigneeZipCode { get; set; }
        public string ConsigneeLocation { get; set; }
        public string ConsigneeDistrict { get; set; }
        public string ConsigneeRegion { get; set; }
        public string ConsigneeCountry { get; set; }
        public Nullable<int> UnloadID { get; set; }
        public string UnloadName { get; set; }
        public string UnloadAddress { get; set; }
        public string UnloadZipCode { get; set; }
        public string UnloadLocation { get; set; }
        public string UnloadDistrict { get; set; }
        public string UnloadRegion { get; set; }
        public string UnloadCountry { get; set; }
        public string UnloadCode { get; set; }
        public string LogWareID { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public string StatusTypeFrom { get; set; }
        public string SiteID { get; set; }
        public string TxToSiteID { get; set; }
        public string StatusDes { get; set; }
        public string ItemColor { get; set; }
        public Nullable<int> ShipUniq { get; set; }
        public Nullable<byte> ShipDoctip { get; set; }
        public string ShipDocNum { get; set; }
        public string ShipLoadCarrierDes { get; set; }
        public string ShipUnLoadCarrierDes { get; set; }
        public string TripUnloadCarrierDes { get; set; }
        public string TripDriverDes { get; set; }
        public string TripVehicleID { get; set; }
        public string TripDocNum { get; set; }
        public Nullable<int> TripUniq { get; set; }
        public Nullable<System.DateTime> ShipUnloadDate { get; set; }
        public Nullable<System.DateTime> TripStartDate { get; set; }
        public string TripStartTime { get; set; }
        public string TripHolderID { get; set; }
        public string TripServiceType { get; set; }
        public string TripTransportType { get; set; }
        public string ItemInfo { get; set; }
        public Nullable<System.DateTime> ShipDta { get; set; }
        public bool ShipMandatory { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> TotalPacks { get; set; }
        public Nullable<decimal> TotalBoxes { get; set; }
        public Nullable<decimal> TotalPallets { get; set; }
        public Nullable<int> TotalPltsOut { get; set; }
        public Nullable<decimal> TotalNetWeight { get; set; }
        public Nullable<decimal> TotalGrossWeight { get; set; }
        public Nullable<decimal> TotalCube { get; set; }
        public Nullable<decimal> TotalCostPrice { get; set; }
        public Nullable<decimal> TotalSellPrice { get; set; }
        public string LastLog { get; set; }
        public Nullable<int> DocNextCount { get; set; }
        public Nullable<int> DocPrecCount { get; set; }
        public Nullable<int> DocLinkedCount { get; set; }
        public string RptId { get; set; }
        public Nullable<int> EpalNo { get; set; }
        public Nullable<int> PltFloor { get; set; }
        public string Info1 { get; set; }
        public string Info2 { get; set; }
        public string Info3 { get; set; }
        public string Info4 { get; set; }
        public string Info5 { get; set; }
        public string Info6 { get; set; }
        public string Info7 { get; set; }
        public string Info8 { get; set; }
        public string Info9 { get; set; }
        public Nullable<int> MissionToDo { get; set; }
        public string DeliveryDock { get; set; }
        public Nullable<System.DateTime> DtaTracking { get; set; }
        public string StatusType { get; set; }
        public string ExternalID { get; set; }
    }
}
