//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRENA_ERIS_DOCUMENT_SERVICE.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEO_IT
    {
        public long ID_GEOGRAFICO { get; set; }
        public string CAP { get; set; }
        public string CITTA { get; set; }
        public string REGIONE { get; set; }
        public string PROVINCIA { get; set; }
        public Nullable<int> ABITANTI { get; set; }
        public string CODICE_ISTAT { get; set; }
    }
}
