//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNITEX_DOCUMENT_SERVICE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAGRAFICA_FORNITORI
    {
        public long ID { get; set; }
        public string ID_GESPE { get; set; }
        public string NOME { get; set; }
        public string PATH_IN { get; set; }
        public string PATH_OUT { get; set; }
        public string EMAILS { get; set; }
    }
}
