//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNITEX_DOCUMENT_SERVICE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEO
    {
        public long Geo_Id { get; set; }
        public string Geo_Location { get; set; }
        public string Geo_ZipCode { get; set; }
        public string Geo_District { get; set; }
        public string Geo_Region { get; set; }
        public string Geo_IstatCode { get; set; }
    }
}
