//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UNITEX_DOCUMENT_SERVICE.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class va_bolle_sat
    {
        public long id_bol_trasporto { get; set; }
        public Nullable<long> id_esercizio { get; set; }
        public Nullable<long> id_filiale { get; set; }
        public string cod_esercizio { get; set; }
        public string cod_filiale { get; set; }
        public Nullable<decimal> prog_spedizione { get; set; }
        public Nullable<System.DateTime> data_spedizione { get; set; }
        public string espresso { get; set; }
        public string rag_soc_mittente { get; set; }
        public string ind_mittente { get; set; }
        public string cap_mittente { get; set; }
        public string citta_mittente { get; set; }
        public string prov_mittente { get; set; }
        public string citta_sede_mittente { get; set; }
        public string rag_soc_destinatario { get; set; }
        public string ind_destinatario { get; set; }
        public string cap_destinatario { get; set; }
        public string citta_destinatario { get; set; }
        public string prov_destinatario { get; set; }
        public string citta_sede_destinatario { get; set; }
        public Nullable<long> id_sog_com_fatturazione { get; set; }
        public string cod_cliente { get; set; }
        public string rag_cliente { get; set; }
        public string tipo_consegna { get; set; }
        public string num_ddt { get; set; }
        public Nullable<System.DateTime> data_ddt { get; set; }
        public string altro_riferimento { get; set; }
        public Nullable<decimal> num_colli { get; set; }
        public Nullable<decimal> peso_effettivo { get; set; }
        public Nullable<decimal> metri_cubi { get; set; }
        public string mis_colli { get; set; }
        public string note_bolla { get; set; }
        public Nullable<System.DateTime> data_cons_tassativa { get; set; }
        public string data_appuntamento { get; set; }
        public Nullable<decimal> num_dist_cliente { get; set; }
        public Nullable<System.DateTime> data_dist_cliente { get; set; }
        public Nullable<System.DateTime> data_cons_richiesta { get; set; }
        public string note_web { get; set; }
        public Nullable<decimal> bancali { get; set; }
        public string tipo_data_tassativa { get; set; }
        public string attesa_pren { get; set; }
        public Nullable<System.DateTime> data_attesa_pren { get; set; }
        public Nullable<long> id_loc_provenienza { get; set; }
        public Nullable<long> id_loc_destinazione { get; set; }
        public string des_contenuto { get; set; }
        public Nullable<decimal> peso_volumizzato { get; set; }
        public Nullable<decimal> contrassegno { get; set; }
        public Nullable<decimal> anticipate { get; set; }
        public Nullable<long> id_tab_iva { get; set; }
        public Nullable<System.DateTime> data_ora_inserimento { get; set; }
        public Nullable<System.DateTime> data_ora_ult_variazione { get; set; }
        public string note_fattura { get; set; }
        public string tariffa_forfait { get; set; }
        public string prima_fascia_oraria { get; set; }
        public string seconda_fascia_oraria { get; set; }
        public string nazione_mittente { get; set; }
        public string nazione_destinatario { get; set; }
        public string tel_destinatario { get; set; }
        public string note_incasso { get; set; }
        public Nullable<decimal> epal { get; set; }
        public string tipo_inc_richiesto { get; set; }
        public string email { get; set; }
        public Nullable<decimal> metri_lineari { get; set; }
        public string collegamento_tc { get; set; }
        public Nullable<decimal> num_colli_tc { get; set; }
        public Nullable<decimal> peso_effettivo_tc { get; set; }
        public Nullable<decimal> metri_cubi_tc { get; set; }
        public Nullable<decimal> bancali_tc { get; set; }
        public string sec_riferimento { get; set; }
        public string adr { get; set; }
        public Nullable<decimal> mit_longitudine { get; set; }
        public Nullable<decimal> mit_latitudine { get; set; }
        public Nullable<decimal> dest_longitudine { get; set; }
        public Nullable<decimal> dest_latitudine { get; set; }
        public string note_ritiro { get; set; }
        public Nullable<System.DateTime> data_pronto_merce { get; set; }
        public string tel_mittente { get; set; }
        public string regione_mit { get; set; }
        public string regione_dest { get; set; }
    }
}
