//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anagrafica_Prodotti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anagrafica_Prodotti()
        {
            this.G_Podotto_Categoria = new HashSet<G_Podotto_Categoria>();
            this.ListinoCommissioni = new HashSet<ListinoCommissioni>();
        }
    
        public long ID_ANAGRAFICA_PRODOTTO { get; set; }
        public string CODICE_PRODOTTO { get; set; }
        public string DESCRIZIONE_PRODOTTO { get; set; }
        public Nullable<decimal> PREZZO_UNITARIO { get; set; }
        public System.DateTime DATA_CREAZIONE { get; set; }
        public System.DateTime DATA_ULTIMA_MODIFICA { get; set; }
        public string GESPE_CUSTOMERID { get; set; }
        public string CODICE_IVA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Podotto_Categoria> G_Podotto_Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListinoCommissioni> ListinoCommissioni { get; set; }
    }
}
