//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ANAGRAFICA_MANDANTI
    {
        public long ID_ANAGRAFICA_MANDANTE { get; set; }
        public string ID_MANDANTE_GESPE { get; set; }
        public string NOME_MANDANTE { get; set; }
        public bool NOTIFICA_GIACENZE { get; set; }
        public System.DateTime DATA_ULTIMA_NOTIFICA_GIACENZE { get; set; }
        public bool NOTIFICA_MOV_MAG { get; set; }
        public System.DateTime DATA_ULTIMA_NOTIFICA_MOVI_MAG { get; set; }
        public string MAIL_NOTIFICA_GIACENZE { get; set; }
        public string MAIL_NOTIFICA_MOV_MAG { get; set; }
        public bool INVIA_DOCUMENTO_BEM { get; set; }
        public string MAIL_NOTIFICA_BEM { get; set; }
        public bool NOTIFICA_TRACKING { get; set; }
        public string MAIL_TRACKING { get; set; }
    }
}
