//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class APS_DAFNE
    {
        public string CODICE_PRODOTTO { get; set; }
        public int IVA_PRODOTTO { get; set; }
        public decimal PREZZO_PRODOTTO { get; set; }
        public decimal SCONTO_PRODOTTO { get; set; }
        public string VALUTA_PRODOTTO { get; set; }
    }
}
