//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categorie_Prodotti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categorie_Prodotti()
        {
            this.G_Categorie_Subcategorie = new HashSet<G_Categorie_Subcategorie>();
            this.G_Podotto_Categoria = new HashSet<G_Podotto_Categoria>();
        }
    
        public long ID_CATEGORIA { get; set; }
        public string DESCRIZIONE { get; set; }
        public decimal PERCENTUALE_COMMISSIONE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Categorie_Subcategorie> G_Categorie_Subcategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_Podotto_Categoria> G_Podotto_Categoria { get; set; }
    }
}
