//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_Authorization
    {
        public string Customer_Id { get; set; }
        public Nullable<System.DateTime> LastModifiedDate { get; set; }
        public string LastModifiedUserID { get; set; }
        public Nullable<System.DateTime> ExpireDateTracking { get; set; }
        public int Tracking_Active { get; set; }
        public Nullable<System.DateTime> ExpireDateWarehouse { get; set; }
        public int Warehouse_Active { get; set; }
        public Nullable<System.DateTime> ExpireDateOrders { get; set; }
        public int Orders_Active { get; set; }
        public Nullable<System.DateTime> ExpireDateAgents { get; set; }
        public int Agents_Active { get; set; }
        public Nullable<System.DateTime> ExpireDateAnagrafiche { get; set; }
        public int Anagrafiche_Active { get; set; }
        public Nullable<System.DateTime> ExpireDateHome { get; set; }
        public int Home_Active { get; set; }
        public Nullable<System.DateTime> ExpireDateRegistration { get; set; }
        public int Registration_Active { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
