//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Client_User = new HashSet<Client_User>();
            this.Customer_Client = new HashSet<Customer_Client>();
            this.Customer_CustomData = new HashSet<Customer_CustomData>();
            this.User = new HashSet<User>();
            this.Customer_RegType = new HashSet<Customer_RegType>();
        }
    
        public string Customer_id { get; set; }
        public string Customer_SessionID { get; set; }
        public string Customer_description { get; set; }
        public bool Customer_isEnable { get; set; }
        public string Customer_address { get; set; }
        public string Customer_zipCode { get; set; }
        public string Customer_location { get; set; }
        public string Customer_district { get; set; }
        public string Customer_country { get; set; }
        public string Customer_defaultPriceListId { get; set; }
        public string Customer_vatCode { get; set; }
        public bool Customer_IsEnableCRM { get; set; }
        public byte[] Customer_Logo { get; set; }
        public System.DateTime Customer_CreationDate { get; set; }
        public System.DateTime Customer_LastModifiedDate { get; set; }
        public string Customer_LastModifiedUserID { get; set; }
        public string Customer_EspritecAPI_Username { get; set; }
        public string Customer_EspritecAPI_Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Client_User> Client_User { get; set; }
        public virtual Customer_Authorization Customer_Authorization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_Client> Customer_Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_CustomData> Customer_CustomData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customer_RegType> Customer_RegType { get; set; }
    }
}
