//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_ListiniAgenti
    {
        public long ID_G_LISTINO_AGENTE { get; set; }
        public string FK_USER { get; set; }
        public long FK_LISTINO { get; set; }
    
        public virtual ListinoCommissioni ListinoCommissioni { get; set; }
        public virtual User User { get; set; }
    }
}
