//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class G_Podotto_Categoria
    {
        public long ID_Prodotto_Categoria { get; set; }
        public long FK_ANAGRAFICA_ARTICOLO { get; set; }
        public long FK_CATEGORIA { get; set; }
    
        public virtual Anagrafica_Prodotti Anagrafica_Prodotti { get; set; }
        public virtual Categorie_Prodotti Categorie_Prodotti { get; set; }
    }
}
