//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListinoCommissioni
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ListinoCommissioni()
        {
            this.G_ListiniAgenti = new HashSet<G_ListiniAgenti>();
        }
    
        public long ID_LISTINO { get; set; }
        public long FK_ANAGRAFICA_PRODOTTO { get; set; }
        public decimal PERCENTUALE_COMMISSIONE { get; set; }
    
        public virtual Anagrafica_Prodotti Anagrafica_Prodotti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<G_ListiniAgenti> G_ListiniAgenti { get; set; }
    }
}
