//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XCM_CRMEntities : DbContext
    {
        public XCM_CRMEntities()
            : base("name=XCM_CRMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Client_Location> Client_Location { get; set; }
        public virtual DbSet<Client_User> Client_User { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Customer_Authorization> Customer_Authorization { get; set; }
        public virtual DbSet<Customer_Client> Customer_Client { get; set; }
        public virtual DbSet<Customer_CustomData> Customer_CustomData { get; set; }
        public virtual DbSet<ListinoCommissioni> ListinoCommissioni { get; set; }
        public virtual DbSet<ShipmentList> ShipmentList { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<AgentAuthorization> AgentAuthorization { get; set; }
        public virtual DbSet<Anagrafica_Prodotti> Anagrafica_Prodotti { get; set; }
        public virtual DbSet<Categorie_Prodotti> Categorie_Prodotti { get; set; }
        public virtual DbSet<Cd_PG> Cd_PG { get; set; }
        public virtual DbSet<Customer_RegType> Customer_RegType { get; set; }
        public virtual DbSet<G_Categorie_Subcategorie> G_Categorie_Subcategorie { get; set; }
        public virtual DbSet<G_ListiniAgenti> G_ListiniAgenti { get; set; }
        public virtual DbSet<G_Podotto_Categoria> G_Podotto_Categoria { get; set; }
        public virtual DbSet<GEO> GEO { get; set; }
        public virtual DbSet<Order_Agent> Order_Agent { get; set; }
        public virtual DbSet<Order_Client> Order_Client { get; set; }
        public virtual DbSet<Orders_RegType> Orders_RegType { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Subcategorie_Prodotti> Subcategorie_Prodotti { get; set; }
        public virtual DbSet<Tracking> Tracking { get; set; }
    }
}
