//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_Client
    {
        public long OrdersClient_ID { get; set; }
        public Nullable<long> UnloadLocationID { get; set; }
        public long ConsigneeLocationID { get; set; }
        public string FK_OrdersClient_Client_ID { get; set; }
        public long FK_OrdersClient_OrdersID { get; set; }
    
        public virtual Customer_Client Customer_Client { get; set; }
    }
}
