//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class uvwWmsWarehouse
    {
        public int uniq { get; set; }
        public string SiteID { get; set; }
        public Nullable<int> LocID { get; set; }
        public string LocDes { get; set; }
        public string LocAlias { get; set; }
        public string MapID { get; set; }
        public string LocCol { get; set; }
        public string LocRow { get; set; }
        public string LocFloor { get; set; }
        public string LocType { get; set; }
        public string PrdCod { get; set; }
        public string PrdDes { get; set; }
        public string ProducerID { get; set; }
        public string ProducerDes { get; set; }
        public string OwnerID { get; set; }
        public string OwnerDes { get; set; }
        public string CustomerID { get; set; }
        public string CustomerDes { get; set; }
        public Nullable<int> ItemStatus { get; set; }
        public string StatusDes { get; set; }
        public string StatusColor { get; set; }
        public string StatusType { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public Nullable<System.DateTime> DateInShort { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> DateRef { get; set; }
        public string Barcode { get; set; }
        public string BarcodeExt { get; set; }
        public string BarcodeMaster { get; set; }
        public string BatchNo { get; set; }
        public Nullable<System.DateTime> DateExpire { get; set; }
        public string DateExpireISO { get; set; }
        public Nullable<System.DateTime> DateExpireTS { get; set; }
        public Nullable<int> ShelfLifeAvailable { get; set; }
        public int ShelfLifeAvailablePerc { get; set; }
        public Nullable<System.DateTime> DateProd { get; set; }
        public Nullable<decimal> TotalQtyAbs { get; set; }
        public Nullable<decimal> TotalQty { get; set; }
        public Nullable<decimal> TotalQtyAvailable { get; set; }
        public Nullable<decimal> BoxQty { get; set; }
        public Nullable<decimal> BoxNo { get; set; }
        public Nullable<decimal> PackQty { get; set; }
        public Nullable<decimal> PackNo { get; set; }
        public Nullable<decimal> TotalNetWeight { get; set; }
        public Nullable<decimal> TotalGrossWeight { get; set; }
        public Nullable<decimal> TotalCube { get; set; }
        public Nullable<decimal> VarWeight { get; set; }
        public Nullable<decimal> VarWeightUnitPrice { get; set; }
        public string LogWareID { get; set; }
        public string Project { get; set; }
        public string SubProject { get; set; }
        public string Variant1 { get; set; }
        public string Variant2 { get; set; }
        public string Variant3 { get; set; }
        public string Variant4 { get; set; }
        public string Variant5 { get; set; }
        public Nullable<System.DateTime> RecCreate { get; set; }
        public Nullable<int> RecUserID { get; set; }
        public Nullable<System.DateTime> RecChange { get; set; }
        public Nullable<int> RecChangeUserID { get; set; }
        public string LastLog { get; set; }
        public Nullable<int> InRegID { get; set; }
        public string RegTypeID { get; set; }
        public string RegTypeDes { get; set; }
        public string ItemInfo1 { get; set; }
        public string ItemInfo2 { get; set; }
        public string ItemInfo3 { get; set; }
        public string ItemInfo4 { get; set; }
        public string ItemInfo5 { get; set; }
        public Nullable<int> LinkDocId { get; set; }
        public Nullable<byte> LinkDocTip { get; set; }
        public string LinkDocNum { get; set; }
        public string TxToSiteID { get; set; }
        public string TxToLogWareID { get; set; }
        public string PAckageID { get; set; }
        public Nullable<decimal> Height { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Deep { get; set; }
        public Nullable<int> OutShelfLife { get; set; }
        public Nullable<int> ProcID { get; set; }
        public string ProcDes { get; set; }
        public Nullable<int> PRocType { get; set; }
        public Nullable<decimal> QtyMission { get; set; }
        public Nullable<int> MissionCount { get; set; }
        public string PrdUm { get; set; }
        public string PrdGroup { get; set; }
        public string PrdCat { get; set; }
        public string PrdClass { get; set; }
        public Nullable<byte> PrdKind { get; set; }
        public string PrdBrand { get; set; }
        public string PrdBrandDes { get; set; }
        public Nullable<decimal> PrdDeliveryQtyBox { get; set; }
        public string PrdKindDes { get; set; }
        public Nullable<System.DateTime> DtaLastInventory { get; set; }
        public Nullable<int> UserLastInventory { get; set; }
        public string OrderDocNum { get; set; }
        public Nullable<int> OrderUniq { get; set; }
        public string OrderReference { get; set; }
        public Nullable<System.DateTime> LocDtaLastInventory { get; set; }
        public Nullable<int> LocUserLastInventory { get; set; }
        public Nullable<int> SenderID { get; set; }
        public string SenderName { get; set; }
        public string SenderAddress { get; set; }
        public string SenderLocation { get; set; }
        public string SenderZipCode { get; set; }
        public string SenderDistrict { get; set; }
        public string SenderRegion { get; set; }
        public string SenderCountry { get; set; }
        public Nullable<int> ConsigneeID { get; set; }
        public string ConsigneeName { get; set; }
        public string ConsigneeAddress { get; set; }
        public string ConsigneeLocation { get; set; }
        public string ConsigneeZipCode { get; set; }
        public string ConsigneeDistrict { get; set; }
        public string ConsigneeRegion { get; set; }
        public string ConsigneeCountry { get; set; }
        public Nullable<int> UnloadID { get; set; }
        public string UnloadName { get; set; }
        public string UnloadAddress { get; set; }
        public string UnloadLocation { get; set; }
        public string UnloadZipCode { get; set; }
        public string UnloadDistrict { get; set; }
        public string UnloadRegion { get; set; }
        public string UnloadCountry { get; set; }
        public string HubID { get; set; }
        public string DogCod { get; set; }
        public string OrderRowNote { get; set; }
        public Nullable<System.DateTime> QuarantineExpire { get; set; }
    }
}
