//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XCM_DOCUMENT_SERVICE.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewSerialSpec
    {
        public Nullable<int> UniqFrom { get; set; }
        public string PrdCod { get; set; }
        public string PrdDes { get; set; }
        public string SerialNumber { get; set; }
        public int Uniq { get; set; }
        public string WareBarcode { get; set; }
    }
}
